function out1 = Ae_cst_func(in1,in2,in3)
%Ae_cst_func
%    OUT1 = Ae_cst_func(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    18-Jan-2024 10:00:00

xe11 = in1(1,:);
xe12 = in1(2,:);
xe21 = in2(1,:);
xe22 = in2(2,:);
xe31 = in3(1,:);
xe32 = in3(2,:);
out1 = (xe11.*xe22)./2.0-(xe12.*xe21)./2.0-(xe11.*xe32)./2.0+(xe12.*xe31)./2.0+(xe21.*xe32)./2.0-(xe22.*xe31)./2.0;
end
