function [Be_u,Be_theta,Be_w] = Be_Mindlin_func(in1,in2,in3,in4,in5)
%Be_Mindlin_func
%    [Be_u,Be_theta,Be_w] = Be_Mindlin_func(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    20-Feb-2024 14:04:07

xe11 = in2(1,:);
xe12 = in2(2,:);
xe21 = in3(1,:);
xe22 = in3(2,:);
xe31 = in4(1,:);
xe32 = in4(2,:);
xe41 = in5(1,:);
xe42 = in5(2,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
t2 = xe11.*xe22;
t3 = xe12.*xe21;
t4 = xe11.*xe42;
t5 = xe12.*xe41;
t6 = xe21.*xe32;
t7 = xe22.*xe31;
t8 = xe31.*xe42;
t9 = xe32.*xe41;
t10 = xe11.*xi1;
t11 = xe11.*xi2;
t12 = xe12.*xi1;
t13 = xe12.*xi2;
t14 = xe21.*xi1;
t15 = xe21.*xi2;
t16 = xe22.*xi1;
t17 = xe22.*xi2;
t18 = xe31.*xi1;
t19 = xe31.*xi2;
t20 = xe32.*xi1;
t21 = xe32.*xi2;
t22 = xe41.*xi1;
t23 = xe41.*xi2;
t24 = xe42.*xi1;
t25 = xe42.*xi2;
t26 = t2.*xi2;
t27 = t3.*xi2;
t28 = t10.*xe32;
t29 = t12.*xe31;
t30 = t11.*xe32;
t31 = t13.*xe31;
t32 = t4.*xi1;
t33 = t5.*xi1;
t34 = t6.*xi1;
t35 = t7.*xi1;
t36 = t14.*xe42;
t37 = t16.*xe41;
t38 = t15.*xe42;
t39 = t17.*xe41;
t40 = t8.*xi2;
t41 = t9.*xi2;
t46 = -t3;
t47 = -t4;
t48 = -t7;
t49 = -t9;
t51 = -t11;
t53 = -t13;
t54 = -t15;
t55 = -t17;
t57 = -t19;
t59 = -t21;
t60 = -t23;
t61 = -t25;
t62 = -t26;
t63 = -t28;
t64 = -t31;
t65 = -t33;
t66 = -t35;
t67 = -t36;
t68 = -t38;
t69 = -t41;
t78 = t2+t5+t6+t8+t27+t29+t30+t32+t34+t37+t39+t40+t46+t47+t48+t49+t62+t63+t64+t65+t66+t67+t68+t69;
t79 = 1.0./t78;
t81 = -t79.*(t12-t16+t21+t55-xe12+xe32);
t82 = -t79.*(t10-t14+t23+t51-xe21+xe41);
t84 = -t79.*(t11+t18-t22+t60-xe11+xe31);
t87 = -t79.*(t17+t20-t24+t59-xe22+xe42);
t88 = t79.*(t10-t14+t19+t54-xe11+xe31);
t89 = t79.*(t12-t16+t25+t53-xe22+xe42);
t90 = t79.*(t13+t20-t24+t61-xe12+xe32);
t91 = t79.*(t15+t18-t22+t57-xe21+xe41);
Be_u = reshape([t87,0.0,t91,0.0,t91,t87,t90,0.0,t84,0.0,t84,t90,t89,0.0,t82,0.0,t82,t89,t81,0.0,t88,0.0,t88,t81],[3,8]);
if nargout > 1
    Be_theta = reshape([t87,0.0,t91,0.0,t91,t87,t90,0.0,t84,0.0,t84,t90,t89,0.0,t82,0.0,t82,t89,t81,0.0,t88,0.0,t88,t81],[3,8]);
end
if nargout > 2
    Be_w = reshape([t87,t91,t90,t84,t89,t82,t81,t88],[2,4]);
end
end
