function [Be,detFisop,N_w] = Vert_Be_quad_func(in1,in2,in3,in4,in5)
%Vert_Be_quad_func
%    [Be,detFisop,N_w] = Vert_Be_quad_func(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Feb-2024 12:10:39

xe11 = in2(1,:);
xe12 = in2(2,:);
xe21 = in3(1,:);
xe22 = in3(2,:);
xe31 = in4(1,:);
xe32 = in4(2,:);
xe41 = in5(1,:);
xe42 = in5(2,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
t2 = xe11.*xe22;
t3 = xe12.*xe21;
t4 = xe11.*xe42;
t5 = xe12.*xe41;
t6 = xe21.*xe32;
t7 = xe22.*xe31;
t8 = xe31.*xe42;
t9 = xe32.*xe41;
t10 = xe11.*xi1;
t11 = xe11.*xi2;
t12 = xe12.*xi1;
t13 = xe12.*xi2;
t14 = xe21.*xi1;
t15 = xe21.*xi2;
t16 = xe22.*xi1;
t17 = xe22.*xi2;
t18 = xe31.*xi1;
t19 = xe31.*xi2;
t20 = xe32.*xi1;
t21 = xe32.*xi2;
t22 = xe41.*xi1;
t23 = xe41.*xi2;
t24 = xe42.*xi1;
t25 = xe42.*xi2;
t26 = xi2+1.0;
t47 = xi2-1.0;
t64 = xi1./4.0;
t27 = t2.*xi2;
t28 = t3.*xi2;
t29 = t10.*xe32;
t30 = t12.*xe31;
t31 = t11.*xe32;
t32 = t13.*xe31;
t33 = t4.*xi1;
t34 = t5.*xi1;
t35 = t6.*xi1;
t36 = t7.*xi1;
t37 = t14.*xe42;
t38 = t16.*xe41;
t39 = t15.*xe42;
t40 = t17.*xe41;
t41 = t8.*xi2;
t42 = t9.*xi2;
t48 = -t3;
t49 = -t4;
t50 = -t7;
t51 = -t9;
t53 = -t11;
t55 = -t13;
t56 = -t15;
t57 = -t17;
t59 = -t19;
t61 = -t21;
t62 = -t23;
t63 = -t25;
t73 = t64+1.0./4.0;
t74 = t64-1.0./4.0;
t65 = -t27;
t66 = -t29;
t67 = -t32;
t68 = -t34;
t69 = -t36;
t70 = -t37;
t71 = -t39;
t72 = -t42;
t83 = t2+t5+t6+t8+t28+t30+t31+t33+t35+t38+t40+t41+t48+t49+t50+t51+t65+t66+t67+t68+t69+t70+t71+t72;
t84 = 1.0./t83;
t86 = -t84.*(t12-t16+t21+t57-xe12+xe32);
t87 = -t84.*(t10-t14+t23+t53-xe21+xe41);
t89 = -t84.*(t11+t18-t22+t62-xe11+xe31);
t92 = -t84.*(t17+t20-t24+t61-xe22+xe42);
t93 = t84.*(t10-t14+t19+t56-xe11+xe31);
t94 = t84.*(t12-t16+t25+t55-xe22+xe42);
t95 = t84.*(t13+t20-t24+t63-xe12+xe32);
t96 = t84.*(t15+t18-t22+t59-xe21+xe41);
Be = reshape([t92,0.0,t96,0.0,t96,t92,t95,0.0,t89,0.0,t89,t95,t94,0.0,t87,0.0,t87,t94,t86,0.0,t93,0.0,t93,t86],[3,8]);
if nargout > 1
    detFisop = t2./8.0-t3./8.0-t4./8.0+t5./8.0+t6./8.0-t7./8.0+t8./8.0-t9./8.0-t27./8.0+t28./8.0-t29./8.0+t30./8.0+t31./8.0-t32./8.0+t33./8.0-t34./8.0+t35./8.0-t36./8.0-t37./8.0+t38./8.0-t39./8.0+t40./8.0+t41./8.0-t42./8.0;
end
if nargout > 2
    N_w = [t47.*t74,-t47.*t73,t26.*t73,-t26.*t74];
end
end
